"""The golden workspace: one app of each stack, generated by the CLI from a committed answers file, deterministic, current and unpackaged."""

from __future__ import annotations

import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

import yaml
from jinja2 import Environment

from prism_cli import cli
from prism_cli.packs import PACK_STACKS
from tests import real_temp  # noqa: F401
from tests.script_support import REPO_ROOT, load_script
from tests.test_repository_hygiene import personal_path_hits

build_golden = load_script("build-golden.py")
GOLDEN = REPO_ROOT / "golden"
CANONICAL = cli.DEFAULT_TEMPLATE_URL

MANIFEST_A = (
    "schema_version: 2\n"
    "generated_by:\n"
    "  tool: prism-cli\n"
    "  template_source: D:\\Somebody\\checkout\\prism\n"
    "  template_version: unversioned\n"
    "  generated_at: '2026-10-07T08:17:08+02:00'\n"
    "project:\n"
    "  name: Prism Golden\n"
    "workflow:\n"
    "  version: '1'\n"
    "  mode: generated\n"
    "  board_id: 6f1d7c52-83a4-4c58-9b0e-2f3a1d4b5c60\n"
    "  asset_digest: " + "a" * 64 + "\n"
)
MANIFEST_B = (
    MANIFEST_A.replace("D:\\Somebody\\checkout\\prism", "/home/runner/work/prism/prism")
    .replace("2026-10-07T08:17:08+02:00", "2027-01-02T03:04:05+00:00")
    .replace("6f1d7c52-83a4-4c58-9b0e-2f3a1d4b5c60", "0b9c4e11-52d7-4f0a-8a6e-9d3c7b2f1e44")
)


class AnswersFileTests(unittest.TestCase):
    def answers(self) -> dict:
        return yaml.safe_load(build_golden.ANSWERS.read_text(encoding="utf-8"))["answers"]

    def test_the_answers_file_is_committed_next_to_the_script_and_fixes_the_project_identity(self) -> None:
        self.assertEqual(REPO_ROOT / "scripts" / "golden-answers.yml", build_golden.ANSWERS)
        answers = self.answers()
        for key in ("project_name", "project_slug", "package_identifier", "description"):
            self.assertTrue(answers.get(key), f"{key} is fixed in the answers file, so the output never depends on a default derived at run time")

    def test_the_golden_workspace_holds_exactly_one_app_of_each_pack_stack(self) -> None:
        stacks = [app["stack"] for app in self.answers()["apps"]]
        self.assertEqual(sorted(PACK_STACKS), sorted(stacks))
        self.assertEqual(len(stacks), len({app["id"] for app in self.answers()["apps"]}))

    def test_the_committed_workspace_has_the_five_apps_their_workflows_and_their_lockfiles(self) -> None:
        manifest = yaml.safe_load((GOLDEN / "prism.workspace.yml").read_text(encoding="utf-8"))
        self.assertEqual(sorted(PACK_STACKS), sorted(app["stack"] for app in manifest["apps"]))
        for app in manifest["apps"]:
            self.assertEqual("scaffolded", app["generation"])
            self.assertTrue((GOLDEN / ".github" / "workflows" / f"{app['id']}.yml").is_file(), app["id"])
            self.assertTrue((GOLDEN / app["path"] / ".copier-answers.yml").is_file(), app["id"])
        self.assertTrue((GOLDEN / "web" / "package-lock.json").is_file())
        self.assertTrue((GOLDEN / "agent-service" / "uv.lock").is_file())
        self.assertTrue((GOLDEN / "backend" / "gradle" / "wrapper" / "gradle-wrapper.properties").is_file())
        self.assertTrue((GOLDEN / "mobile-android" / "gradle" / "wrapper" / "gradle-wrapper.properties").is_file())


class DeterminismTests(unittest.TestCase):
    def test_the_manifest_is_normalized_to_constants_whatever_the_machine_and_the_time(self) -> None:
        a = build_golden.normalize("prism.workspace.yml", MANIFEST_A.encode())
        b = build_golden.normalize("prism.workspace.yml", MANIFEST_B.encode())
        self.assertEqual(a, b)
        text = a.decode()
        self.assertIn(f"  template_source: {CANONICAL}\n", text)
        self.assertIn(f"  generated_at: '{build_golden.FIXED_TIME}'\n", text)
        self.assertIn(f"  board_id: {build_golden.FIXED_BOARD_ID}\n", text, "the board identity is random per workspace, a constant in golden/")
        self.assertIn("  asset_digest: " + "a" * 64 + "\n", text, "the packaged assets' digest is kept as it is")
        self.assertEqual(a, build_golden.normalize("prism.workspace.yml", a), "normalizing twice changes nothing")

    def test_every_answers_file_names_the_canonical_template_source(self) -> None:
        for relative in (".copier-answers.yml", "web/.copier-answers.yml"):
            data = build_golden.normalize(relative, b"_src_path: C:\\Users\\Example\\prism\napp_id: web\n")
            self.assertEqual(f"_src_path: {CANONICAL}\napp_id: web\n".encode(), data)

    def test_line_endings_are_lf_and_binary_files_are_untouched(self) -> None:
        self.assertEqual(b"a\nb\n", build_golden.normalize("backend/gradlew.bat", b"a\r\nb\r\n"))
        jar = b"PK\x03\x04\0\r\n\xff"
        self.assertEqual(jar, build_golden.normalize("backend/gradle/wrapper/gradle-wrapper.jar", jar))

    def test_a_manifest_that_changed_shape_stops_the_build_instead_of_slipping_through(self) -> None:
        with self.assertRaises(SystemExit):
            build_golden.normalize("prism.workspace.yml", b"schema_version: 2\n")

    def test_the_local_env_file_is_not_part_of_the_workspace_and_build_output_folders_are_refused(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            (root / "README.md").write_bytes(b"x\r\n")
            (root / ".env").write_text("DATABASE_PASSWORD=localdev\n", encoding="utf-8")
            self.assertEqual({"README.md": b"x\n"}, build_golden.collect_generated(root))
            (root / "web" / "node_modules").mkdir(parents=True)
            (root / "web" / "node_modules" / "a.js").write_text("x", encoding="utf-8")
            with self.assertRaises(SystemExit):
                build_golden.collect_generated(root)

    def test_a_path_of_the_machine_in_the_output_is_refused(self) -> None:
        temporary = Path(tempfile.gettempdir()) / "prism-golden-x"
        with self.assertRaises(SystemExit):
            build_golden.guard_machine_values({"a.txt": f"see {temporary}\n".encode()}, temporary)
        build_golden.guard_machine_values({"a.txt": b"nothing local\n", "b.bin": b"\0" + str(temporary).encode()}, temporary)

    def test_the_comparison_ignores_line_endings_and_build_output_and_reports_every_kind_of_difference(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            (root / "same.txt").write_bytes(b"a\r\nb\r\n")  # a checkout with CRLF
            (root / "changed.txt").write_bytes(b"old\n")
            (root / "stale.txt").write_bytes(b"stale\n")
            (root / "web" / "node_modules").mkdir(parents=True)
            (root / "web" / "node_modules" / "left-by-npm-ci.js").write_bytes(b"x")
            generated = {"same.txt": b"a\nb\n", "changed.txt": b"new\n", "added.txt": b"added\n"}
            missing, extra, changed = build_golden.differences(generated, build_golden.collect_existing(root))
            self.assertEqual((["added.txt"], ["stale.txt"], ["changed.txt"]), (missing, extra, changed))

    def test_writing_adds_changes_and_removes_files_leaves_current_ones_and_keeps_build_output(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary) / "golden"
            (root / "gone").mkdir(parents=True)
            (root / "gone" / "file.txt").write_bytes(b"x\n")
            (root / "web" / "node_modules").mkdir(parents=True)
            (root / "web" / "node_modules" / "keep.js").write_bytes(b"x")
            (root / "same.txt").write_bytes(b"same\n")
            (root / "changed.txt").write_bytes(b"old\n")
            counts = build_golden.write({"same.txt": b"same\n", "changed.txt": b"new\n", "deep/er/added.txt": b"added\n"}, root)
            self.assertEqual((1, 1, 1), counts)
            self.assertEqual(b"new\n", (root / "changed.txt").read_bytes())
            self.assertEqual(b"added\n", (root / "deep" / "er" / "added.txt").read_bytes())
            self.assertFalse((root / "gone").exists(), "a folder the removed files emptied goes with them")
            self.assertTrue((root / "web" / "node_modules" / "keep.js").is_file())
            self.assertEqual((0, 0, 0), build_golden.write({"same.txt": b"same\n", "changed.txt": b"new\n", "deep/er/added.txt": b"added\n"}, root))


class CommittedWorkspaceTests(unittest.TestCase):
    def committed_files(self) -> dict[str, bytes]:
        return build_golden.collect_existing(GOLDEN)

    def test_no_file_of_the_workspace_holds_a_personal_path_or_a_local_env_file(self) -> None:
        files = self.committed_files()
        self.assertTrue(files, "golden/ is empty; run `python scripts/build-golden.py`")
        self.assertNotIn(".env", files)
        findings = []
        for name, data in files.items():
            if build_golden.is_binary(data):
                continue
            for number, line in enumerate(data.decode("utf-8", "replace").splitlines(), start=1):
                findings.extend(f"{name}:{number}: {hit}" for hit in personal_path_hits(line))
        self.assertEqual([], findings)

    def test_what_building_leaves_behind_is_neither_compared_nor_removed(self) -> None:
        """The CI jobs build the golden apps in place; a local `npm run build` leaves ignored files that are not part of the workspace."""

        if build_golden.run_git(["rev-parse", "--git-dir"]) is None:
            self.skipTest("git is unavailable or the repository has no git metadata")
        # The files are written into a scratch repository that carries the repository's own ignore files, never
        # into golden/ itself: another test running at the same time (in another process) reads the whole checkout.
        with tempfile.TemporaryDirectory() as temporary:
            scratch = Path(temporary)
            subprocess.run(["git", "init", "-q"], cwd=scratch, check=True, capture_output=True)
            for ignore in (".gitignore", "golden/.gitignore", "golden/web/.gitignore"):
                (scratch / ignore).parent.mkdir(parents=True, exist_ok=True)
                (scratch / ignore).write_bytes((REPO_ROOT / ignore).read_bytes())
            golden = scratch / "golden"
            leftover = golden / "web" / "lib" / "api" / "generated" / "left-by-a-local-build.d.ts"
            stray = golden / "web" / "stray-file-nobody-generates.txt"
            leftover.parent.mkdir(parents=True, exist_ok=True)
            leftover.write_text("leftover", encoding="utf-8")
            stray.write_text("stray", encoding="utf-8")
            with patch.object(build_golden, "ROOT", scratch), patch.object(build_golden, "GOLDEN", golden):
                ignored = build_golden.untracked_ignored()
                self.assertIn("web/lib/api/generated/left-by-a-local-build.d.ts", ignored)
                self.assertNotIn("web/stray-file-nobody-generates.txt", ignored)
                existing = build_golden.collect_existing(golden, ignored)
            self.assertNotIn("web/lib/api/generated/left-by-a-local-build.d.ts", existing)
            self.assertIn("web/stray-file-nobody-generates.txt", existing, "an untracked file that git would commit is a difference")

    def test_the_gitignore_probe_names_the_files_git_would_keep_out_of_a_commit(self) -> None:
        if build_golden.run_git(["rev-parse", "--git-dir"]) is None:
            self.skipTest("git is unavailable or the repository has no git metadata")
        self.assertEqual(
            ["mobile-android/app/build/outputs/app.apk"],
            build_golden.git_ignored(["web/package.json", "mobile-android/app/build/outputs/app.apk", "backend/build.gradle.kts"]),
        )
        self.assertEqual([], build_golden.git_ignored(["web/package.json"]))
        self.assertEqual([], build_golden.git_ignored([]))

    def test_every_answers_file_and_the_manifest_carry_the_constants(self) -> None:
        files = self.committed_files()
        answers_files = [name for name in files if name.endswith(".copier-answers.yml")]
        self.assertEqual(6, len(answers_files), "the workspace layer and five apps")
        for name in answers_files:
            self.assertIn(f"_src_path: {CANONICAL}\n", files[name].decode(), name)
        manifest = files["prism.workspace.yml"].decode()
        self.assertIn(f"  generated_at: '{build_golden.FIXED_TIME}'\n", manifest)
        self.assertIn(f"  template_source: {CANONICAL}\n", manifest)

    def test_the_committed_workspace_equals_a_fresh_generation(self) -> None:
        """The check CI runs as its own job: a template change that does not refresh golden/ fails here and there."""

        result = subprocess.run(
            [sys.executable, "-B", str(REPO_ROOT / "scripts" / "build-golden.py"), "--check"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            timeout=900,
        )
        self.assertEqual(0, result.returncode, result.stdout + result.stderr)


class ExcludedFromTheTemplateAndThePackageTests(unittest.TestCase):
    def test_the_template_root_of_every_layer_is_the_workspace_layer_or_a_pack_never_the_repository_root(self) -> None:
        config = yaml.safe_load((REPO_ROOT / "copier.yml").read_text(encoding="utf-8"))
        subdirectory = Environment().from_string(config["_subdirectory"])
        layers = config["prism_layer"]["choices"]
        rendered = {layer: subdirectory.render(prism_layer=layer) for layer in layers}
        self.assertEqual({"workspace": "template", **{stack: f"packs/{stack}" for stack in PACK_STACKS}}, rendered)
        self.assertNotIn("golden", "".join(rendered.values()))

    def test_a_local_template_is_staged_without_the_golden_workspace(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            source = Path(temporary) / "prism"
            for relative in (".git/HEAD", "golden/README.md", "golden/web/package.json", "template/golden/keep.txt", "template/README.md", "copier.yml"):
                path = source / relative
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text("x\n", encoding="utf-8")
            with cli.staged_template_path(str(source)) as staged:
                staged_files = sorted(path.relative_to(staged).as_posix() for path in staged.rglob("*") if path.is_file())
            self.assertEqual(["copier.yml", "template/README.md", "template/golden/keep.txt"], staged_files)

    def test_the_source_archive_prunes_the_golden_workspace_and_the_wheel_packages_only_the_cli(self) -> None:
        manifest_in = (REPO_ROOT / "MANIFEST.in").read_text(encoding="utf-8").splitlines()
        self.assertIn("prune golden", manifest_in)
        pyproject = (REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8")
        self.assertIn('packages = ["prism_cli"]', pyproject)
        self.assertIn("include-package-data = false", pyproject)


if __name__ == "__main__":
    unittest.main()
