#!/usr/bin/env python3
"""Build or verify the Codex, Claude and Cursor skill layers of the generated workspace.

``template-skills/<name>/skill.md`` is the one source of a skill. Its front matter names the skill,
gives its one description, lists the layers it ships to and carries the per-host fields; its body
is written once. This script renders every layer file under ``template/`` from those sources:

* ``codex``: ``.agents/skills/<name>/SKILL.md.jinja`` and ``agents/openai.yaml``;
* ``command``: ``.claude/commands/<name>.md.jinja``;
* ``claude-skill``: ``.claude/skills/<name>/SKILL.md.jinja``;
* ``cursor``: ``.cursor/rules/<file>.mdc.jinja``.

A skill's ``references/`` folder is copied to both skill folders. The stack conditions of the
sources fill the generated block of ``_exclude`` in ``copier.yml``: the workspace layer receives the
``stacks`` of its scaffolded apps, and ``app_ids`` for a reference that belongs to one full-sample app.
Everything under the four managed folders is generated; a file there that no source produces is stale.

The body is written once. Two small mechanisms cover the differences between hosts:

* ``@@invoke:<name>@@`` becomes the host's way to run that skill: ``$name`` for Codex, ``/name``
  for a Claude command, and the bare name in a Claude skill or a Cursor rule;
* a block that opens with ``::: only <layers>`` and closes with ``:::`` stays only in those layers.
  The layers are ``codex``, ``command``, ``claude-skill`` and ``cursor``; ``claude`` stands for the
  two Claude layers.

Copier conditions and variables in a body pass through unchanged.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys
from typing import Any

import yaml
from jinja2 import Environment, TemplateSyntaxError


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "template-skills"
TEMPLATE_DIR = ROOT / "template"
COPIER_PATH = ROOT / "copier.yml"

LAYERS = ("codex", "command", "claude-skill", "cursor")
LAYER_GROUPS = {"claude": ("command", "claude-skill")}
# The stacks a skill can need, and the full-sample apps a reference file can belong to.
STACKS = ("spring-backend", "nextjs-web", "android-compose", "ios-swiftui")
SAMPLE_APPS = ("mobile-android", "mobile-ios")
# Everything under these folders of the template is generated from the sources.
MANAGED_ROOTS = (".agents/skills", ".claude/commands", ".claude/skills", ".cursor/rules")
HEADER = "{# Generated from template-skills/%s/skill.md by scripts/build-skill-layers.py. Edit the source, not this file. -#}\n"
BLOCK_BEGIN = "  # BEGIN generated by scripts/build-skill-layers.py: stack exclusions of the skill layers"
BLOCK_END = "  # END generated by scripts/build-skill-layers.py"

_FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
_INVOKE = re.compile(r"@@invoke:([a-z0-9-]+)@@")
_BLOCK_OPEN = re.compile(r"^::: only ([a-z, -]+?)\s*$")
_NAME = re.compile(r"^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$")
_SOURCE_KEYS = {
    "name",
    "description",
    "layers",
    "stacks",
    "reference-stacks",
    "reference-apps",
    "codex",
    "command",
    "claude-skill",
    "cursor",
}
_CODEX_KEYS = ("display_name", "short_description", "default_prompt", "implicit")
_CLAUDE_SKILL_KEYS = ("argument-hint", "disable-model-invocation", "user-invocable", "allowed-tools")


class SkillError(ValueError):
    """A source or a generated file breaks the contract."""


class Skill:
    def __init__(self, directory: Path, metadata: dict[str, Any], body: str) -> None:
        self.directory = directory
        self.name: str = metadata["name"]
        self.description: str = metadata["description"]
        self.layers: tuple[str, ...] = tuple(metadata["layers"])
        self.stacks: tuple[str, ...] = tuple(metadata.get("stacks") or ())
        self.reference_stacks: dict[str, tuple[str, ...]] = {
            key: tuple(value) for key, value in (metadata.get("reference-stacks") or {}).items()
        }
        self.reference_apps: dict[str, tuple[str, ...]] = {
            key: tuple(value) for key, value in (metadata.get("reference-apps") or {}).items()
        }
        self.codex: dict[str, Any] = metadata.get("codex") or {}
        self.command: dict[str, Any] = metadata.get("command") or {}
        self.claude_skill: dict[str, Any] = metadata.get("claude-skill") or {}
        self.cursor: dict[str, Any] = metadata.get("cursor") or {}
        self.body = body

    @property
    def source_path(self) -> str:
        return f"template-skills/{self.name}/skill.md"

    @property
    def cursor_file(self) -> str:
        return str(self.cursor.get("file") or self.name)

    def has(self, layer: str) -> bool:
        return layer in self.layers


def _fail(skill: str, message: str) -> SkillError:
    return SkillError(f"template-skills/{skill}/skill.md: {message}")


def _check_scope(skill: str, key: str, items: Any, allowed: tuple[str, ...]) -> None:
    if not isinstance(items, list) or not items or any(item not in allowed for item in items):
        raise _fail(skill, f"{key} must be a non-empty list of {', '.join(allowed)}.")


def parse_source(directory: Path) -> Skill:
    path = directory / "skill.md"
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    match = _FRONTMATTER.match(text)
    if not match:
        raise SkillError(f"template-skills/{directory.name}/skill.md: missing YAML front matter.")
    try:
        metadata = yaml.safe_load(match.group(1))
    except yaml.YAMLError as exc:
        raise SkillError(f"template-skills/{directory.name}/skill.md: invalid front matter: {exc}") from exc
    name = directory.name
    if not isinstance(metadata, dict):
        raise _fail(name, "front matter must be a mapping.")
    unknown = sorted(set(metadata) - _SOURCE_KEYS)
    if unknown:
        raise _fail(name, f"unknown front matter keys: {', '.join(unknown)}.")
    if metadata.get("name") != name or not _NAME.match(name):
        raise _fail(name, f"name must equal the folder name {name!r} (lowercase words joined by hyphens).")
    description = metadata.get("description")
    if not isinstance(description, str) or not description.strip() or "\n" in description:
        raise _fail(name, "description must be one non-empty line.")
    metadata["description"] = description.strip()
    layers = metadata.get("layers")
    if not isinstance(layers, list) or not layers or any(layer not in LAYERS for layer in layers) or len(set(layers)) != len(layers):
        raise _fail(name, f"layers must be a non-empty list of distinct values from {', '.join(LAYERS)}.")
    if "stacks" in metadata:
        _check_scope(name, "stacks", metadata["stacks"], STACKS)
    for key, value in (metadata.get("reference-stacks") or {}).items():
        _check_scope(name, f"reference-stacks[{key}]", value, STACKS)
    for key, value in (metadata.get("reference-apps") or {}).items():
        _check_scope(name, f"reference-apps[{key}]", value, SAMPLE_APPS)
    if (metadata.get("reference-stacks") or metadata.get("reference-apps")) and not any(layer in layers for layer in ("codex", "claude-skill")):
        raise _fail(name, "reference-stacks and reference-apps need a skill layer (codex or claude-skill).")

    codex = metadata.get("codex") or {}
    if "codex" in layers:
        missing = [key for key in _CODEX_KEYS if key not in codex]
        extra = sorted(set(codex) - set(_CODEX_KEYS))
        if missing or extra or not isinstance(codex.get("implicit"), bool):
            raise _fail(name, f"codex needs {', '.join(_CODEX_KEYS)} (implicit is true or false); missing {missing}, unexpected {extra}.")
        for key in _CODEX_KEYS[:3]:
            if not isinstance(codex[key], str) or not codex[key].strip():
                raise _fail(name, f"codex.{key} must be a non-empty string.")
    elif codex:
        raise _fail(name, "codex fields are set but codex is not a layer.")
    claude_skill = metadata.get("claude-skill") or {}
    if set(claude_skill) - set(_CLAUDE_SKILL_KEYS):
        raise _fail(name, f"claude-skill keys must be among {', '.join(_CLAUDE_SKILL_KEYS)}.")
    if claude_skill and "claude-skill" not in layers:
        raise _fail(name, "claude-skill fields are set but claude-skill is not a layer.")
    if metadata.get("command") and "command" not in layers:
        raise _fail(name, "command fields are set but command is not a layer.")
    cursor = metadata.get("cursor") or {}
    if "cursor" in layers:
        if set(cursor) - {"file", "globs", "always-apply"} or not (("globs" in cursor) ^ ("always-apply" in cursor)):
            raise _fail(name, "cursor takes file (optional) and exactly one of globs or always-apply.")
        if "globs" in cursor and not isinstance(cursor["globs"], str):
            raise _fail(name, "cursor.globs must be a string.")
        if "always-apply" in cursor and not isinstance(cursor["always-apply"], bool):
            raise _fail(name, "cursor.always-apply must be true or false.")
        if not _NAME.match(str(cursor.get("file") or name)):
            raise _fail(name, "cursor.file must be a lowercase hyphenated name.")
    elif cursor:
        raise _fail(name, "cursor fields are set but cursor is not a layer.")

    body = text[match.end() :].strip("\n")
    if not body.strip():
        raise _fail(name, "the body is empty.")
    return Skill(directory, metadata, body)


def load_sources(source_dir: Path = SOURCE_DIR) -> list[Skill]:
    if not source_dir.is_dir():
        raise SkillError(f"{source_dir.name} is missing.")
    skills: list[Skill] = []
    for entry in sorted(source_dir.iterdir(), key=lambda item: item.name):
        if not entry.is_dir() or not (entry / "skill.md").is_file():
            raise SkillError(f"{source_dir.name}/{entry.name} is not a skill folder with a skill.md.")
        skills.append(parse_source(entry))
    seen_cursor: dict[str, str] = {}
    for skill in skills:
        if skill.has("cursor"):
            if skill.cursor_file in seen_cursor:
                raise _fail(skill.name, f"cursor file {skill.cursor_file!r} is also produced by {seen_cursor[skill.cursor_file]}.")
            seen_cursor[skill.cursor_file] = skill.name
        for path in sorted(skill.directory.rglob("*")):
            if path.is_file() and path.name != "skill.md":
                relative = path.relative_to(skill.directory).as_posix()
                if not relative.startswith("references/"):
                    raise _fail(skill.name, f"{relative}: support files live under references/.")
                if not (skill.has("codex") or skill.has("claude-skill")):
                    raise _fail(skill.name, "references need a skill layer (codex or claude-skill).")
    return skills


# --------------------------------------------------------------------------- body rendering


def _layer_set(skill: str, names: str, line_number: int) -> set[str]:
    layers: set[str] = set()
    for raw in names.split(","):
        item = raw.strip()
        if item in LAYERS:
            layers.add(item)
        elif item in LAYER_GROUPS:
            layers.update(LAYER_GROUPS[item])
        else:
            raise _fail(skill, f"line {line_number}: unknown layer {item!r} in a block.")
    return layers


def invocation(layer: str, name: str) -> str:
    if layer == "codex":
        return f"${name}"
    if layer == "command":
        return f"/{name}"
    return name


def _ships_for(layer: str) -> tuple[str, ...]:
    """The layers a skill named by an invocation must ship to for it to run in ``layer``."""

    if layer == "codex":
        return ("codex",)
    if layer in ("command", "claude-skill"):
        return ("command", "claude-skill")
    return ("codex", "command", "claude-skill")


def render_text(skill: Skill, layer: str, text: str, by_name: dict[str, Skill]) -> str:
    def replace(match: re.Match[str]) -> str:
        target = by_name.get(match.group(1))
        if target is None or not any(target.has(item) for item in _ships_for(layer)):
            raise _fail(skill.name, f"@@invoke:{match.group(1)}@@ names no skill that ships to the {layer} layer.")
        return invocation(layer, match.group(1))

    text = _INVOKE.sub(replace, text)
    if "@@" in text:
        raise _fail(skill.name, "an '@@' token is not a known mechanism.")
    return text


def render_body(skill: Skill, layer: str, by_name: dict[str, Skill]) -> str:
    """The body for one layer: blocks for other layers dropped, invocations in the host's form."""

    kept: list[str] = []
    active: set[str] | None = None
    just_dropped = False
    for number, line in enumerate(skill.body.split("\n"), start=1):
        opened = _BLOCK_OPEN.match(line)
        if opened:
            if active is not None:
                raise _fail(skill.name, f"line {number}: blocks do not nest.")
            active = _layer_set(skill.name, opened.group(1), number)
            continue
        if line.strip() == ":::":
            if active is None:
                raise _fail(skill.name, f"line {number}: a closing ':::' without an open block.")
            just_dropped = layer not in active
            active = None
            continue
        if line.startswith(":::"):
            raise _fail(skill.name, f"line {number}: unrecognised block line {line!r}.")
        if active is None or layer in active:
            # A dropped block leaves one blank line between its neighbours, not two.
            if not (just_dropped and not line.strip() and kept and not kept[-1].strip()):
                kept.append(line)
            just_dropped = False
    if active is not None:
        raise _fail(skill.name, "a block is not closed.")
    return render_text(skill, layer, "\n".join(kept), by_name)


# --------------------------------------------------------------------------- front matter scalars


def yaml_scalar(value: Any) -> str:
    """A front matter value: plain when YAML reads it back as the same string, else double-quoted."""

    if isinstance(value, bool):
        return "true" if value else "false"
    text = str(value)
    try:
        plain_ok = yaml.safe_load(f"key: {text}") == {"key": text}
    except yaml.YAMLError:
        plain_ok = False
    if plain_ok and text == text.strip() and not text.startswith(('"', "'", "[", "{", "&", "*", "!", "|", ">", "%", "@", "`", "#")):
        return text
    return json.dumps(text, ensure_ascii=False)


def _front_matter(pairs: list[tuple[str, Any]]) -> str:
    return "---\n" + "".join(f"{key}: {yaml_scalar(value)}\n" for key, value in pairs) + "---\n"


# --------------------------------------------------------------------------- layer files


def render_layers(skills: list[Skill]) -> dict[str, bytes]:
    """Every generated file under ``template/``, keyed by its path relative to ``template/``."""

    by_name = {skill.name: skill for skill in skills}
    files: dict[str, bytes] = {}

    def put(path: str, content: str | bytes) -> None:
        if path in files:
            raise SkillError(f"{path} is produced twice.")
        files[path] = content.encode("utf-8") if isinstance(content, str) else content

    for skill in skills:
        header = HEADER % skill.name
        if skill.has("codex"):
            body = render_body(skill, "codex", by_name)
            front = _front_matter([("name", skill.name), ("description", skill.description)])
            put(f".agents/skills/{skill.name}/SKILL.md.jinja", header + front + "\n" + body + "\n")
            prompt = {key: render_text(skill, "codex", skill.codex[key].strip(), by_name) for key in _CODEX_KEYS[:3]}
            put(
                f".agents/skills/{skill.name}/agents/openai.yaml",
                "interface:\n"
                f"  display_name: {json.dumps(prompt['display_name'], ensure_ascii=False)}\n"
                f"  short_description: {json.dumps(prompt['short_description'], ensure_ascii=False)}\n"
                f"  default_prompt: {json.dumps(prompt['default_prompt'], ensure_ascii=False)}\n"
                "policy:\n"
                f"  allow_implicit_invocation: {'true' if skill.codex['implicit'] else 'false'}\n",
            )
        if skill.has("command"):
            body = render_body(skill, "command", by_name)
            front = _front_matter(list(skill.command.items())) + "\n" if skill.command else ""
            put(f".claude/commands/{skill.name}.md.jinja", header + front + body + "\n")
        if skill.has("claude-skill"):
            body = render_body(skill, "claude-skill", by_name)
            pairs: list[tuple[str, Any]] = [("name", skill.name), ("description", skill.description)]
            pairs.extend((key, skill.claude_skill[key]) for key in _CLAUDE_SKILL_KEYS if key in skill.claude_skill)
            put(f".claude/skills/{skill.name}/SKILL.md.jinja", header + _front_matter(pairs) + "\n" + body + "\n")
        if skill.has("cursor"):
            body = render_body(skill, "cursor", by_name)
            lines = ["---", f"description: {json.dumps(skill.description, ensure_ascii=False)}"]
            if "globs" in skill.cursor:
                lines.append(f"globs: {json.dumps(skill.cursor['globs'], ensure_ascii=False)}")
            else:
                lines.append(f"alwaysApply: {'true' if skill.cursor['always-apply'] else 'false'}")
            lines.append("---")
            put(f".cursor/rules/{skill.cursor_file}.mdc.jinja", header + "\n".join(lines) + "\n\n" + body + "\n")
        if skill.has("codex") or skill.has("claude-skill"):
            for path in sorted(skill.directory.glob("references/**/*")):
                if not path.is_file():
                    continue
                relative = path.relative_to(skill.directory).as_posix()
                data = path.read_bytes().replace(b"\r\n", b"\n")
                for layer, folder in (("codex", ".agents/skills"), ("claude-skill", ".claude/skills")):
                    if skill.has(layer):
                        put(f"{folder}/{skill.name}/{relative}", data)
    for path, data in files.items():
        if path.endswith(".jinja"):
            _check_jinja(path, data.decode("utf-8"))
    return files


def _check_jinja(path: str, text: str) -> None:
    extensions: list[str] = []
    try:
        import jinja2_time  # noqa: F401

        extensions.append("jinja2_time.TimeExtension")
    except ImportError:
        pass
    try:
        Environment(extensions=extensions).parse(text)
    except TemplateSyntaxError as exc:
        raise SkillError(f"{path}: not valid Jinja ({exc.message}, line {exc.lineno}).") from exc


# --------------------------------------------------------------------------- copier.yml block


def _exclude_line(scope: tuple[str, ...], path: str, variable: str = "stacks") -> str:
    """One ``_exclude`` entry: the path goes unless one of the stacks (or full-sample app IDs) is present.

    The entry applies to the workspace layer only; an app layer's paths are its own.
    """

    condition = " and ".join(f"'{item}' not in {variable}" for item in scope)
    return f'  - "{{% if prism_layer == \'workspace\' and {condition} %}}{path}{{% endif %}}"'


def _reference_names(skill: Skill) -> set[str]:
    """The rendered names of a skill's reference files and of every folder above them."""

    names: set[str] = set()
    for path in skill.directory.glob("references/**/*"):
        if not path.is_file():
            continue
        rendered = Path(path.relative_to(skill.directory).as_posix().removesuffix(".jinja"))
        names.add(rendered.as_posix())
        names.update(parent.as_posix() for parent in rendered.parents if parent.as_posix() not in {".", ""})
    return names


def exclude_lines(skills: list[Skill]) -> list[str]:
    lines: list[str] = []
    for skill in skills:
        if skill.stacks:
            paths: list[str] = []
            if skill.has("codex"):
                paths.append(f".agents/skills/{skill.name}")
            if skill.has("command"):
                paths.append(f".claude/commands/{skill.name}.md")
            if skill.has("claude-skill"):
                paths.append(f".claude/skills/{skill.name}")
            if skill.has("cursor"):
                paths.append(f".cursor/rules/{skill.cursor_file}.mdc")
            lines.extend(_exclude_line(skill.stacks, path) for path in paths)
        names = _reference_names(skill)
        for key, scopes, variable in (
            ("reference-stacks", skill.reference_stacks, "stacks"),
            ("reference-apps", skill.reference_apps, "app_ids"),
        ):
            for relative, scope in scopes.items():
                if relative not in names:
                    raise _fail(skill.name, f"{key} names {relative!r}, which no reference file or folder has.")
                for layer, folder in (("codex", ".agents/skills"), ("claude-skill", ".claude/skills")):
                    if skill.has(layer):
                        lines.append(_exclude_line(scope, f"{folder}/{skill.name}/{relative}", variable))
    return lines


def render_copier(current: str, skills: list[Skill]) -> str:
    text = current.replace("\r\n", "\n")
    begin = text.find(BLOCK_BEGIN)
    end = text.find(BLOCK_END)
    if begin < 0 or end < begin:
        raise SkillError(f"copier.yml has no generated block between '{BLOCK_BEGIN.strip()}' and '{BLOCK_END.strip()}'.")
    end_of_line = text.find("\n", end)
    block = "\n".join([BLOCK_BEGIN, *exclude_lines(skills), BLOCK_END])
    return text[:begin] + block + text[end_of_line:]


# --------------------------------------------------------------------------- the managed folders


def _normalize(data: bytes) -> bytes:
    return data.replace(b"\r\n", b"\n")


def existing_files(template: Path = TEMPLATE_DIR) -> dict[str, bytes]:
    found: dict[str, bytes] = {}
    for managed in MANAGED_ROOTS:
        base = template / managed
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*")):
            if path.is_file():
                found[path.relative_to(template).as_posix()] = path.read_bytes()
    return found


def differences(skills: list[Skill], template: Path = TEMPLATE_DIR, copier_path: Path = COPIER_PATH) -> list[str]:
    """The generated files that differ from the sources: missing, stale or changed."""

    expected = render_layers(skills)
    current = existing_files(template)
    problems: list[str] = []
    for path in sorted(expected):
        if path not in current:
            problems.append(f"missing: template/{path}")
        elif _normalize(current[path]) != _normalize(expected[path]):
            problems.append(f"differs from its source: template/{path}")
    for path in sorted(set(current) - set(expected)):
        problems.append(f"no source produces: template/{path}")
    wanted = render_copier(copier_path.read_text(encoding="utf-8"), skills)
    if _normalize(copier_path.read_bytes()) != wanted.encode("utf-8"):
        problems.append("differs from its sources: the generated _exclude block of copier.yml")
    return problems


def write(skills: list[Skill], template: Path = TEMPLATE_DIR, copier_path: Path = COPIER_PATH) -> list[str]:
    expected = render_layers(skills)
    current = existing_files(template)
    changed: list[str] = []
    for path, data in sorted(expected.items()):
        if path in current and _normalize(current[path]) == _normalize(data):
            continue
        target = template / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        changed.append(path)
    for path in sorted(set(current) - set(expected)):
        (template / path).unlink()
        changed.append(f"{path} (removed)")
    for managed in MANAGED_ROOTS:
        base = template / managed
        if base.is_dir():
            for directory in sorted((item for item in base.rglob("*") if item.is_dir()), key=lambda item: len(item.parts), reverse=True):
                if not any(directory.iterdir()):
                    directory.rmdir()
    wanted = render_copier(copier_path.read_text(encoding="utf-8"), skills)
    if _normalize(copier_path.read_bytes()) != wanted.encode("utf-8"):
        copier_path.write_bytes(wanted.encode("utf-8"))
        changed.append("copier.yml")
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="Fail when a generated file differs from its source.")
    args = parser.parse_args()
    try:
        skills = load_sources()
        if args.check:
            problems = differences(skills)
            if problems:
                print("The generated skill layers are out of date; edit template-skills/ and run scripts/build-skill-layers.py:", file=sys.stderr)
                for problem in problems:
                    print(f"  {problem}", file=sys.stderr)
                return 1
            print(f"PASS: {len(skills)} skill sources match the generated layers under template/")
            return 0
        changed = write(skills)
    except (OSError, SkillError) as exc:
        print(f"Skill layer build failed: {exc}", file=sys.stderr)
        return 1
    print(f"Generated {len(skills)} skill sources; {len(changed)} file(s) changed.")
    for path in changed:
        print(f"  {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
